### ISSUE TITLE
Seeing code garbage in result

### ISSUE THREAD

**Issue by soheilshiri** [micromatch/to-regex-range#3] opened 2017-08-23 09:53 UTC
Hi,

I am using your amazing lib but it makes kinda wrong responses. The issue is that I am seeing some parts of String object in result. Check the following please:

Example:

toRegexRange(5, 9)

makes this:

regex:  /1[5-9]function (search, replacement) {
    var target = this;
    return target.split(search).join(replacement);
}function (it) {
    return this.indexOf(it) != -1;
}|[2-8]function (search, replacement) {
    var target = this;
    return target.split(search).join(replacement);
}function (it) {
    return this.indexOf(it) != -1;
}[0-9]|9[0-5]function (search, replacement) {
    var target = this;
    return target.split(search).join(replacement);
}function (it) {
    return this.indexOf(it) != -1;
}/

**Comment by doowb** [comment] 2017-08-23 14:02
@soheilshiri I'm unable to reproduce the results. This is what I get when I run:

```js
var toRegexRange = require('to-regex-range');
console.log(toRegexRange(5, 9));
//=> [5-9]
```

Do you have any more information you can share?
- node version
- OS version
- are you passing additional options to `toRegexRange`?

**Comment by jonschlinkert** [comment] 2017-08-23 15:51
I don't see how this library would create that result. there are no constructors.

**Comment by amirsedighi** [comment] 2017-08-25 09:08
Hi Owner,

I just fixed the issue by calling zip() like this:
var zipped = zip(start.toString().split(''), stop.toString().split(''));

String(start) ( As you already have in your code) makes "start" an object. So it makes the result full of containing characters such as what Soheilshiri has mentioned.

Regards,
Amir

**Comment by jonschlinkert** [comment] 2017-10-19 13:45
Hi Commenter, something else must be happening, I can't reproduce the bug based on the code that was given. 

Closing since none of the information requested by @doowb was provided and we can't reproduce the bug.

**Closed by jonschlinkert** 2017-10-19 13:45 UTC
